code --install-extensions 8amjp.charactercount
code --install-extensions alexcvzz.vscode-sqlite
code --install-extensions batisteo.vscode-django
code --install-extensions bbrakenhoff.solarized-light-custom
code --install-extensions bibhasdn.django-html
code --install-extensions chrmarti.regex
code --install-extensions CoenraadS.bracket-pair-colorizer-2
code --install-extensions donjayamanne.githistory
code --install-extensions donjayamanne.python-extension-pack
code --install-extensions eamodio.gitlens
code --install-extensions emmanuelbeziat.vscode-great-icons
code --install-extensions fivethree.vscode-ionic-snippets
code --install-extensions formulahendry.auto-close-tag
code --install-extensions formulahendry.auto-rename-tag
code --install-extensions formulahendry.code-runner
code --install-extensions formulahendry.terminal
code --install-extensions goessner.mdmath
code --install-extensions golang.go
code --install-extensions Gruntfuggly.activitusbar
code --install-extensions hediet.vscode-drawio
code --install-extensions hollowtree.vue-snippets
code --install-extensions ionutvmi.path-autocomplete
code --install-extensions k--kato.intellij-idea-keybindings
code --install-extensions loiane.ionic-extension-pack
code --install-extensions magicstack.MagicPython
code --install-extensions mariorodeghiero.vue-theme
code --install-extensions marp-team.marp-vscode
code --install-extensions mechatroner.rainbow-csv
code --install-extensions mgmcdermott.vscode-language-babel
code --install-extensions mrmlnc.vscode-duplicate
code --install-extensions ms-azuretools.vscode-docker
code --install-extensions MS-CEINTL.vscode-language-pack-ja
code --install-extensions ms-mssql.mssql
code --install-extensions ms-python.python
code --install-extensions ms-vscode-remote.remote-containers
code --install-extensions ms-vscode.cpptools
code --install-extensions mtxr.sqltools
code --install-extensions octref.vetur
code --install-extensions oderwat.indent-rainbow
code --install-extensions peakchen90.open-html-in-browser
code --install-extensions PKief.material-icon-theme
code --install-extensions redhat.vscode-yaml
code --install-extensions rust-lang.rust
code --install-extensions ryu1kn.partial-diff
code --install-extensions shardulm94.trailing-spaces
code --install-extensions shd101wyy.markdown-preview-enhanced
code --install-extensions steoates.autoimport
code --install-extensions tht13.python
code --install-extensions tomoki1207.pdf
code --install-extensions tushortz.python-extended-snippets
code --install-extensions vadimcn.vscode-lldb
code --install-extensions VisualStudioExptTeam.vscodeintellicode
code --install-extensions vscode-icons-team.vscode-icons
code --install-extensions wholroyd.jinja
code --install-extensions xabikos.JavaScriptSnippets
code --install-extensions xaver.clang-format
code --install-extensions yzane.markdown-pdf
code --install-extensions yzhang.markdown-all-in-one
